### ISSUE TITLE
2017 is preprinted in K4 pdf

### ISSUE THREAD

**Issue by PhotolyzeAnt** [bitsofwinter/cryptotaxsweden#15]
Very minor issue, but I was generating a correction for 2016 and noticed that 2017 is preprinted in the K4 pdf.

**Comment by bitsofwinter** [comment]
Yep, didn't think anyone would notice until sometime in 2019 though. ;-)

Do you know where to find a pdf-template without the preprinted year? I'm not sure how I can remove it from the existing document.

**Comment by Sire** [comment]
I removed the 2017 at top. There is still a serial nr at the bottom with 2017 in it however. So we still might have to upload a new file next year.
PDF: [K4.pdf](https://github.com/bitsofwinter/cryptotaxsweden/files/1994367/K4.pdf)
Service used: https://smallpdf.com/edit-pdf

**Comment by bitsofwinter** [comment]
Yes, I guess the serial number / bar code makes it hard to autogenerate for any year. I could add support for storing a different template pdf for each year though so that the risk of using the template for the wrong year is minimized. I.e. it would be better if the script refused to generate a K4 pdf for 2018 before there is a template available for 2018. SRU-generation will always work for any year though as it doesn't have the same kind of serial numbers in it.

**Comment by Sire** [comment]
Sounds like the best solution under the circumstances.
